name: CI

on:
  push:
    branches:
      - ci/dependency-caching 
  pull_request:
    branches:
      - main

jobs:
  compile_and_verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache pnpm and node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Cache asdf tools
        uses: actions/cache@v3
        with:
          path: |
            ~/.asdf
            ~/.cache/scarb
            ~/.cache/starknet-foundry
          key: asdf-${{ runner.os }}-${{ hashFiles('.tool-versions') }}
          restore-keys: |
            asdf-${{ runner.os }}-

      - name: Install asdf & tools # For multiple versions of scarb - reads from .tool-versions and installs them
        uses: asdf-vm/actions/install@v3

      - name: Set default scarb version # First version in .tool-versions
        run: asdf global scarb $(cat .tool-versions | grep scarb | cut -d ' ' -f 2)

      - name: Setup Starknet-Foundry
        uses: foundry-rs/setup-snfoundry@v3

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: rust-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            rust-${{ runner.os }}-

      - name: Setup Rust cache
        uses: ./.github/workflows/setup-rust-cache

      - name: Cache mdbook dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: mdbook-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            mdbook-${{ runner.os }}-

      - name: Install mdbook
        uses: ./.github/workflows/install-mdbook

      - name: Build book (English)
        run: mdbook build -d book

      - name: Install cairo-listings
        run: cargo install --path cairo-listings --locked
        shell: bash

      - name: Run cairo-listings and generate summary
        run: cairo-listings verify >> $GITHUB_STEP_SUMMARY
        shell: bash

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master